version: '3'
services:
  backend:
    build: ./crypto-portfolio-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./crypto-portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

